### ISSUE TITLE
Volumes on CIFS share 

### ISSUE THREAD

**Issue by fabioxp7980** [ngosang/docker-amule#12]
Sorry for the dumb question but I have no knowledge on lot of Linux commands, I have a proxmox machine where I try several things, one of them is this amule image running in an unprivileged debian ct. I have a Lacie Wireless Space network drive with only CIFS support. I made some search and found that I can use bind mounts to have files shared between the ct and the host, however if I download for example a video and then do a filetype search, I see the downloaded file is a folder like this

./var/lib/docker/overlay2/VERYLONGALPHANUMERICSTRING/merged/incoming/DOWNLOADEDVIDEO.mkv

so the file is not visible at the shared lan drive, I know this is a strange setup, I ask also for the future, it will be easier to use for example a Synology NAS using NFS share for this amule image? maybe not so usefull if I can install amule directly on the NAS.

I know this is NOT AN ISSUE but hope someone can help me.

**Comment by ngosang** [comment]
Sorry for the late response.
First of all, using CIFS / Samba for file sharing is possible but not recommended because the network access to files is slow.
If you want to access the files inside the container, you have to use Docker volumes. You can map the host path with a path inside the container. In this case the external path could be your CIFS folder. Take a look at the provided docker-compose => https://github.com/ngosang/docker-amule/blob/e08ac26cda0c4608a3837f651f233ce52ab9f5bd/docker-compose.yml#L26
