### ISSUE TITLE
Kad connection error

### ISSUE THREAD

**Issue by Manuel5cc** [ngosang/docker-amule#33]
Seems that Kad network is unable to connect. Everything else is OK with the ed2k server connected and high. The only information in the logs referring to Kad is this:

`Kad started.`

The fix for the graph is activated.

**Comment by cenosito** [comment]
La red Kad tarda en conectarse un buen rato, dale tiempo. Si tienes ID alta en ed2k la red Kad te conectará también.

**Comment by Manuel5cc** [comment]
> La red Kad tarda en conectarse un buen rato, dale tiempo. Si tienes ID alta en ed2k la red Kad te conectará también.

It's been more than 12 hours running and still is not connected. Should it take that long? Back when I used desktop apps it was a matter of minutes.

**Comment by cenosito** [comment]
> > La red Kad tarda en conectarse un buen rato, dale tiempo. Si tienes ID alta en ed2k la red Kad te conectará también.
> 
> It's been more than 12 hours running and still is not connected. Should it take that long? Back when I used desktop apps it was a matter of minutes.

No, no debe tardar tanto. Creo que la primera vez que arranqué el contenedor me tardó entre 10 min y 1 Hora conectar.

Te dejo lo que dice la página oficial del proyecto aMule, puedes leer y averiguar por ti mismo.

> Why does Kademlia still say it is "firewalled"?
If you are using Kad and your router is doing NAT (Network Address Translation), you should prevent your router from remapping the port of outgoing UDP port 4672 packets. This might help if you have a high ID but Kad status is 'firewalled'. Also, note that many ISPs now have filters on port 4662, which result in the "KAD: firewalled" status. To resolve this, follow these steps:

Pick a number n so that 80 < n < 65530
set Preferences ---> Connection ---> standard client TCP port to n
forward (as shown in faqs) the following three ports: tcp port n (instead of 4662), udp port n+3 (instead of 4665), udp port 4672
finally, update the node list (in Networks ---> Kad), and have some patience (5 minutes or so)
if you still don't have green arrows, you may want to try a different n
Here's a list of n's that worked, please add: 4811, 9870

[https://wiki.amule.org/wiki/FAQ_eD2k-Kademlia](url)

**Comment by toketin** [comment]
Hi, I've switched from Debian's repo aMule to this docker container and I confirm that the Kad network isn't connecting.

**Comment by ngosang** [comment]
The first start it takes like 10 minutes. After that it's really fast.
Did you open these ports in your router? https://github.com/ngosang/docker-amule#application-setup
Coud you check if you can download this file? https://github.com/ngosang/docker-amule/blob/df1ff4777cbe356d0f243be4d6d8c4c04dedbbf9/entrypoint.sh#L213

**Comment by ngosang** [comment]
Fixed in https://github.com/ngosang/docker-amule/releases/tag/2.3.3-15
