### ISSUE TITLE
Kad nodes graph is missing

### ISSUE THREAD

**Issue by garret** [ngosang/docker-amule#8]
Hi, first of all thank you very much for your docker image. I am using it on a rpi and it works wonderfully. Hope you can continue the updates when they come out. 

I have only one issue, that the KAD graph seems missing (even though aMule is connected to KAD with high ID). I attach a screenshot to explain it better: 
![image](https://user-images.githubusercontent.com/27555/151658587-569313e0-6e59-4d50-bade-d258cfd6b817.png)

The same graph is missing when you go to the "Stats" page (but all the other graphs like "Connection Counts", "Downloads" and "Uploads" appear instead). 

Do you know how to fix this?

**Comment by ngosang** [comment]
Thanks for reporting the issue. There is an important issue in aMule source code that crash the whole application when you request the Kad graph.

aMule issue => https://github.com/amule-project/amule/issues/265

Since the issue is not fixed and there is not much activity in the project, I fixed it my Docker image just by removing the image. In that way it's not requested to the server and aMule does not crash. You can see my workaround here => https://github.com/ngosang/docker-amule/blob/eda654c340979a4f76731b2c376188a93c2ff672/Dockerfile#L28

**Comment by garret** [comment]
Ok, I can live with that but I was using another docker image with alpine as base image and there is no such issue. Is it due because of the base distro (debian in this case)?

**Comment by ngosang** [comment]
I think it affects all distributions but I just tested Debian package. When aMule starts the image works as expected but **after 3 or 4 days running (without restart)** the number of KAD nodes increases and the program crashes. I think that is because they are using integer types to handle large numbers but I'm not sure.
I can add an environment variable in the Docker image to not remove the images if you want...

**Comment by garret** [comment]
@ngosang I think is ok like this, so no need to make it more complicated. Just wanted to be sure that everything under the hood works as it should. Hopefully, aMule development will resolve the issue in the near future.

**Comment by ngosang** [comment]
Ok. If you are running aMule 24/7 take a look at this => #7
